### ISSUE TITLE
Add deep learning detections

### ISSUE THREAD

**Issue by macster110** [TaikiSan21/PamBinaries#2]
PAMGuard has a new deep learning module which outputs both a new type of detection (a deep learning detection) and adds deep learning annotations to existing data units. There are examples of the functions in [MATLAB PAMGuard library](https://github.com/PAMGuard/PAMGuardMatlab/tree/main/pgmatlab) (readDLAnnotation.m and readDLDetData.m). Could these also be implemented in R? 

See [here](https://github.com/macster110/PAMGuard_resources/blob/main/deep_learning/Deep%20learning%20in%20PAMGuard.pdf) for more info on the PAMGuard deep learning module and example of how to use the MATLAB code.

**Comment by TaikiSan21** [comment]
Done! Tested it on some binary files from that repo, seems to be working. Really neat stuff, hoping we can start trying to use it soon.

**Comment by macster110** [comment]
Awesome, thanks!
